default: &default
  adapter: postgresql
  encoding: unicode
  username: sachin
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: techstar_development

test:
  <<: *default
  database: techstar_test